[package]
name = "encrypted-backup"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "3.2.5", features = ["derive"] }
glob = "0.3.0"
tar = "0.4.38"
aes-gcm = "0.9.4"
sha2 = "0.10.2"
rand = "0.8.5"
tempfile = "3"
